// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gCnfDFBpWXSCMMyA1YKWsTyblu1vfLw',
    appId: '1:813980683743:web:28f774e3173286601fc86a',
    messagingSenderId: '813980683743',
    projectId: 'signein-with-goole',
    authDomain: 'signein-with-goole.firebaseapp.com',
    storageBucket: 'signein-with-goole.appspot.com',
    measurementId: 'G-KVJ07FT38P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGppi-5pNHnCu8P4bVx4O029wGGCo6yE8',
    appId: '1:813980683743:android:a13c1f0f301d90b91fc86a',
    messagingSenderId: '813980683743',
    projectId: 'signein-with-goole',
    storageBucket: 'signein-with-goole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcty9fEqroEj6SbPwTRyVlOsNk9aWMAg',
    appId: '1:813980683743:ios:277e8bb1f86003a31fc86a',
    messagingSenderId: '813980683743',
    projectId: 'signein-with-goole',
    storageBucket: 'signein-with-goole.appspot.com',
    iosClientId: '813980683743-tguegm3he4eqhn988virmhm7qs4ntb2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcty9fEqroEj6SbPwTRyVlOsNk9aWMAg',
    appId: '1:813980683743:ios:277e8bb1f86003a31fc86a',
    messagingSenderId: '813980683743',
    projectId: 'signein-with-goole',
    storageBucket: 'signein-with-goole.appspot.com',
    iosClientId: '813980683743-tguegm3he4eqhn988virmhm7qs4ntb2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinWithFirebase',
  );
}
